# Generated by Django 2.1.3 on 2018-11-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181126_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='teams',
        ),
    ]
