# Generated by Django 2.1.3 on 2018-12-16 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181129_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaT1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'type1'), (2, 'type2')])),
                ('priority', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('criteria_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CriteriaGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriteriaT2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'type1'), (2, 'type2')])),
                ('title', models.CharField(max_length=255)),
                ('criteria_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CriteriaGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
