# Generated by Django 2.1.3 on 2018-12-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_criteriagroup_criteriat1_criteriat2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaClause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Criteria')),
            ],
        ),
        migrations.CreateModel(
            name='SingleCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('criteria_clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CriteriaClause')),
            ],
        ),
        migrations.RemoveField(
            model_name='criteriat1',
            name='criteria_group',
        ),
        migrations.RemoveField(
            model_name='criteriat2',
            name='criteria_group',
        ),
        migrations.DeleteModel(
            name='CriteriaGroup',
        ),
        migrations.DeleteModel(
            name='CriteriaT1',
        ),
        migrations.DeleteModel(
            name='CriteriaT2',
        ),
    ]
