# Generated by Django 2.1.3 on 2019-01-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181217_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ticket'),
        ),
        migrations.AlterField(
            model_name='criteriaclause',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='app.Criteria'),
        ),
        migrations.AlterField(
            model_name='singlecriteria',
            name='criteria_clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles', to='app.CriteriaClause'),
        ),
    ]
