# Generated by Django 2.0.1 on 2019-02-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190206_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Team'),
        ),
    ]
